version: 2
updates:
  - package-ecosystem: "gomod"
    commit-message:
      prefix: "deps:"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "ci:"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
